apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    reloader: enabled
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1>Welcome to Azure AKS!</h1>
    </body>
    </html>
