apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-cpu-alert
  namespace: monitoring
spec:
  groups:
  - name: nginx-alerts
    rules:
    - alert: HighCpuUsage
      expr: sum(rate(container_cpu_usage_seconds_total{pod=~"nginx.*"}[1m])) by (pod) > 0.5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected on NGINX pod"
        description: "The NGINX pod {{ $labels.pod }} is using high CPU. Current value is {{ $value }}."
