apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  endpoints:
  - port: 9113
    interval: 15s
