apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-alertmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 66.2.2
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelector: {}
            podMonitorSelector: {}
        alertmanager:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Optional: Create namespace if
    ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  # hooks:
  # - type: PreSync
  #   resource:
  #     apiVersion: batch/v1
  #     kind: Job
  #     metadata:
  #       name: crd-installer
  #     spec:
  #       template:
  #         spec:
  #           containers:
  #           - name: crd-installer
  #             image: bitnami/kubectl:latest
  #             command:
  #             - /bin/bash
  #             - -c
  #             - |
  #               # List of CRD URLs
  #               CRDS=(
  #                 "https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml"
  #                 "https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml"
  #                 "https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml"
  #                 "https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml"
  #                 "https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml"
  #                 "https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml"
  #                 "https://raw.githubusercontent.com/prometheus-community/helm-charts/main/charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml"
  #               )

  #               # Apply each CRD using server-side apply
  #               for crd in "${CRDS[@]}"; do
  #                 echo "Applying CRD: $crd"
  #                 kubectl apply --server-side -f "$crd"
  #               done

  #               echo "All CRDs applied successfully."

  #           restartPolicy: OnFailure
