apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.30.1
    chart: prometheus
    helm:
      values: |
        serverFiles:
          prometheus.yml:
            global:
              scrape_interval: 15s
            scrape_configs:
              - job_name: 'nginx'
                static_configs:
                  - targets: ['nginx-exporter.monitoring.svc.cluster.local:9113']
        rules:
          nginx-alert-rules.yaml:
            groups:
              - name: nginx-alerts
                rules:
                  - alert: HighCpuUsage
                    expr: sum(rate(container_cpu_usage_seconds_total{job="nginx"}[5m])) > 0.9
                    for: 1m
                    labels:
                      severity: critical
                    annotations:
                      summary: "High CPU usage on Nginx"
                      description: "The Nginx pod is using more than 90% CPU for over 1 minute."
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Optional: Create namespace if
    ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: prometheus-alertmanager
      jsonPointers:
      - /spec/volumeClaimTemplates # Ignore immutable fields in StatefulSet
      - /spec/serviceName
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
