apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-alertmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shovalaharoni99/my-apps.git'
    targetRevision: HEAD
    chart: https://prometheus-community.github.io/helm-charts/kube-prometheus-stack
    helm:
      valueFiles:
      - helm-values/values-prometheus.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Optional: Create namespace if
