# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus-alertmanager
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: 66.2.2
#     chart: kube-prometheus-stack
#     helm:
#       values: |
#       alertmanager:
#         enabled: true
#         config:
#           global:
#             resolve_timeout: 5m
#           route:
#             group_by: [ 'alertname' ]
#             group_wait: 10s
#             group_interval: 10s
#             repeat_interval: 1h
#             receiver: 'console'
#           receivers:
#           - name: 'console'
#             webhook_configs:
#             - url: 'http://localhost:9093' # Logs alerts to console
#           inhibit_rules:
#           - source_match:
#               severity: 'critical'
#             target_match:
#               severity: 'warning'
#             equal: [ 'alertname', 'cluster', 'service' ]

#       prometheus:
#         prometheusSpec:
#           serviceMonitorSelector: {}
#           podMonitorSelector: {}
#           ruleSelector: {}

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true # Optional: Create namespace if
