apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-alertmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 66.2.2
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelector: {}
            podMonitorSelector: {}
        alertmanager:
          enabled: true
          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ['alertname']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: 'console'
            receivers:
              - name: 'console'
                webhook_configs:
                  - url: 'http://localhost:9094'
            inhibit_rules:
              - source_match:
                  severity: 'critical'
                target_match:
                  severity: 'warning'
                equal: ['alertname', 'cluster', 'service']
        prometheusOperator:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Optional: Create namespace if
    ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
