# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus-alertmanager
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: 25.30.1
#     chart: prometheus
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true # Optional: Create namespace if
#     ignoreDifferences:
#     - group: apiextensions.k8s.io
#       kind: CustomResourceDefinition
