apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 1.0.111 # Replace with the desired version
    chart: reloader
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader # Target namespace for Reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Optional: Create namespace if
