alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: [ 'alertname' ]
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'console'
    receivers:
    - name: 'console'
      webhook_configs:
      - url: 'http://localhost:9093' # Logs alerts to console
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: [ 'alertname', 'cluster', 'service' ]

prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    ruleSelector: {}
